"""create mission route and permission tables

Revision ID: 4cd1d3910acb
Revises: fb52c350d5b7
Create Date: 2026-09-17 01:39:31.853237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd1d3910acb'
down_revision: Union[str, Sequence[str], None] = 'fb52c350d5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('misiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('horario_inicio_programado', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misiones_id'), 'misiones', ['id'], unique=False)
    op.create_table('rutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mision_id', sa.Integer(), nullable=False),
    sa.Column('orden_waypoint', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('altitud_metros', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['mision_id'], ['misiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_id'), 'rutas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rutas_id'), table_name='rutas')
    op.drop_table('rutas')
    op.drop_index(op.f('ix_misiones_id'), table_name='misiones')
    op.drop_table('misiones')
    op.drop_table('roles_permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    # ### end Alembic commands ###
